### ISSUE TITLE
Adding the rest of the team on "team" page

### ISSUE THREAD

**Issue by doliG** [Fujicracy/fuji-v1#340]
Add the reste of the team on https://www.fujidao.org/#/about

**Todo**
- [x] Ask the others to send nudes (pictures)
- [x] Update the page
- [ ] Push prod lmao

@iafhurtado @tiagofneto plz send nudes below
- [x] Ask artem
