### ISSUE TITLE
[Vesting & Bonding] Implement Designs into the Front-end

### ISSUE THREAD

**Issue by iafhurtado** [Fujicracy/fuji-v1#387]
**Design:** [figma](https://www.figma.com/file/jebHKdrPZXLKnEk9Vd8vDn/Fuji---Design-files?node-id=11639%3A2405)
**Time estimate:** 2 weeks

**Context**
This ticket will be the Upstream vehicle that will contain any designs provided by Loominate in the area of Vesting & Bonding. Next week we will get together with them to set the scope and begin the work, more to come.

The Bond Factory _will only be enabled_ after the user has locked in his points. In the meantime, the Bond Factory will be greyed out and if the user hovers over the text he/she will see a warning message: "Bond Factory will be available only after locking in your points in the Locking Ceremony tab".

**Todo**
- [x] UI Integration (in progress...)
  - [ ] Link for "trade button"
- [x] User can see his balance of each bonds
- [x] User can buy bonds
- [x] Testing
