### ISSUE TITLE
Coinbase wallet integration

### ISSUE THREAD

**Issue by doliG** [Fujicracy/fuji-v1#447]
**Context**

This ticket is a follow up of the discussion we had with boyan & daigaro today (07/25).

To add coinbase wallet & resolve ENS, we can update the library we use (blocknative). Therefore I closed #436 as won't do.

**Todo**

- [ ] Add coinbase wallet
- [ ] Add ENS resolver (see #204)
- [ ] Update blocknative to latest version if possible

**Resources**

Current: https://yarnpkg.com/package/bnc-onboard, https://docs.blocknative.com/onboard-older-version
New: https://docs.blocknative.com/onboard#
